from selenium.webdriver.common.by import By


class RegisterPageLocators:
    FIRSTNAME = (By.CSS_SELECTOR, '#input-firstname')
    FIRST_NAME_LABEL = (By.CSS_SELECTOR, '#account > div:nth-child(3) > label')
    FIRST_NAME_ERRORMESSAGE = (By.CSS_SELECTOR, '#account > div:nth-child(3) > div > div')
    LASTNAME = (By.XPATH, '//*[@id="input-lastname"]')
    LASTNAME_LABEL = (By.CSS_SELECTOR, '#account > div:nth-child(4) > label')
    LASTNAME_ERRORMESSAGE = (By.CSS_SELECTOR, '#account > div:nth-child(4) > div > div')
    EMAIL = (By.XPATH, '//*[@id="input-email"]')
    EMAIL_LABEL = (By.CSS_SELECTOR, '#account > div:nth-child(5) > label')
    EMAIL_ERRORMESSAGE = (By.CSS_SELECTOR, '//*[@id="input-email"]')
    TELEPHONE = (By.XPATH, '//*[@id="input-telephone"]')
    TELEPHONE_LABEL = (By.CSS_SELECTOR, '#account > div:nth-child(6) > label')
    TELEPHONE_ERRORMESSAGE = (By.CSS_SELECTOR, '#account > div:nth-child(6) > div > div')
    ADDRESS1 = (By.XPATH, '//*[@id="input-address-1"]')
    ADDRESS1_LABEL = (By.CSS_SELECTOR, '#address > div:nth-child(3) > label')
    ADDRESS1_ERRORMESSAGE = (By.CSS_SELECTOR, '#address > div:nth-child(3) > div > div')
    CITY = (By.XPATH, '//*[@id="input-city"]')
    CITY_LABEL = (By.CSS_SELECTOR, '#address > div:nth-child(5) > label')
    CITY_ERRORMESSAGE = (By.CSS_SELECTOR, '#address > div:nth-child(5) > div > div')
    POSTCODE = (By.XPATH, '//*[@id="input-postcode"]')
    POSTCODE_LABEL = (By.CSS_SELECTOR, '#address > div:nth-child(6) > label')
    POSTCODE_ERRORMESSAGE = (By.CSS_SELECTOR, '#address > div:nth-child(6) > div > div')
    DROPDOWN_REGION_STATE = (By.CSS_SELECTOR, '#input-zone')
    DROPDOWN_REGION_STATE_LABEL = (By.CSS_SELECTOR, '#address > div:nth-child(8) > label')
    DROPDOWN_REGION_STATE_ERRORMESSAGE = (By.CSS_SELECTOR, '#address > div:nth-child(8) > div > div')
    COUNTRY = (By.XPATH, '//*[@id="input-country"]')
    COUNTRY_LABEL = (By.CSS_SELECTOR, '#address > div:nth-child(7) > label')
#    COUNTRY_ERRORMESSAGE = (By.CSS_SELECTOR, '//*[@id="input-country"]')
    COUNTRYOPTION = (By.XPATH, '//*[@id="input-country"]/option[2]')
    REGION = (By.ID, 'input-zone')

    REGION_OPTION_Albania = (By.XPATH, '//*[@id="input-zone"]/option[2]')
    PASSWORD = (By.XPATH, '//*[@id="input-password"]')
    PASSWORD_LABEL = (By.CSS_SELECTOR, '#content > form > fieldset:nth-child(3) > div.form-group.required.has-error > label')
    PASSWORD_ERRORMESSAGE = (By.XPATH, '//*[@class="text-danger" and contains(text(),"Password must be between 4 and 20 characters!")]')
    PASSWORDCONFIRM = (By.XPATH, '//*[@id="input-confirm"]')
    PASSWORDCONFIRM_LABEL = (By.CSS_SELECTOR, '//*[@id="content"]/form/fieldset[3]/div[2]/label')
    PASSWORDCONFIRM_ERRORMESSAGE = (By.CSS_SELECTOR, '#content > form > fieldset:nth-child(3) > div.form-group.required.has-error > div > div')
#        (By.XPATH, '//*[@class="text-danger" and contains(text(),"Password confirmation does not match password!")]')
    PRIVACYPOLICYCHECKMARK = (By.XPATH, '//*[@id="content"]/form/div/div/input[1]')
    PRIVACYPOLICYCHECKMARK_LINK = (By.CSS_SELECTOR, '#content > form > div > div > a')
    PRIVACYPOLICYCHECKMARK_ERRORMESSAGE = (By.XPATH, '//*[@class="alert alert-danger" and contains(text()," Warning: You must agree to the Privacy Policy!")]')
    CONTINUEBTN = (By.XPATH, './/input[@class="btn btn-primary"]')
    SUCCESSMESSAGE = (By.XPATH, '//*[@id="content"]/h1')


